---
name: Weekly update
on:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout crawler
        uses: actions/checkout@v4
        with:
          repository: OpenShamela/shamela_crawler
          path: crawler
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Crawl
        run: |
          rm *.json
          cd crawler
          uv run scrapy crawl categories -o ../categories.json -s LOG_LEVEL=INFO
          uv run scrapy crawl authors -o ../authors.json -s LOG_LEVEL=INFO
          uv run scrapy crawl books -o ../books.json -s LOG_LEVEL=INFO
      - name: Commit JSON files
        run: >
          git config --global user.name 'GitHub Action Bot'

          git config --global user.email 'action@github.com'

          git add *.json

          git diff --quiet && git diff --staged --quiet || git commit -m "Update data $(date +'%Y%m%d-%H%M%S')"

          git push
      - name: Minimize uv cache
        run: uv cache prune --ci
